routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin'], function () {
    Auth::routes();
    Route::group(['middleware' => ['auth','role:Super Admin|Dokter|Layanan Reservasi|Calon Pasien']], function () {
      Route::resource('user', 'UserController')->except('destroy');
      Route::put('user/profile/{id}', 'UserController@updateProfil')->name('user.update-profil');
      Route::put('user/profile/password/{id}', 'UserController@updatePassword')->name('user.update-password');
    });
    Route::group(['middleware' => ['auth','role:Super Admin|Dokter|Layanan Reservasi']], function () {
        Route::resource('dashboard', 'DashboardController');
        Route::resource('pertanyaan', 'PertanyaanController')->except('destroy');
        Route::resource('monitoring', 'MonitoringController')->except('destroy');
        Route::resource('skor', 'HasilSkorController')->except('destroy');
        Route::resource('jamsesi', 'JamSesiController')->except('destroy');
        Route::resource('reservasiadmin', 'ReservasiAdminController')->except('destroy');
        Route::resource('poli', 'PoliController')->except('destroy');


        Route::get('polihari/{poli_id}', 'PoliHariController@index')->name('polihari.index');

        Route::get('sesi/{poli_hari_id}', 'SesiController@index')->name('sesi.index');
        Route::get('sesi-create/create', 'SesiController@create')->name('sesi.create');
        Route::post('sesi/store', 'SesiController@store')->name('sesi.store');
        Route::get('sesi/edit/{id}', 'SesiController@edit')->name('sesi.edit');
        Route::put('sesi/update/{id}', 'SesiController@update')->name('sesi.update');

        Route::get('layanan', 'LayananController@index')->name('layanan.index');
        Route::get('layanan/reservasi/{id}', 'LayananController@reservasi')->name('layanan.reservasi');
        Route::get('layanan/ubah-status/{id}', 'LayananController@statusUpdate')->name('layanan.statusUpdate');

        Route::get('layanan/pasien-lama', 'LayananController@pasienLama')->name('layanan.pasienLama');
        Route::get('layanan/pasien-lama/create/{pasien_id}', 'LayananController@pasienLamaCreate')->name('layanan.pasienLamaCreate');
        Route::post('layanan/pasien-lama/store/{pasien_id}', 'LayananController@pasienLamaStore')->name('layanan.pasienLamaStore');

        Route::get('layanan/pasien-baru', 'LayananController@pasienBaru')->name('layanan.pasienBaru');
        Route::post('layanan/pasien-baru/store', 'LayananController@pasienBaruStore')->name('layanan.pasienBaruStore');

        Route::get('layanan/cek/{poli_id}', 'LayananController@poliCek')->name('layanan.poliCek');

        Route::get('panggil-antrian/{antrian}/{kode}', 'ReservasiAdminController@panggilAntrian');
        Route::get('antrian/{tipe}/{antrian}/{kode}', 'ReservasiAdminController@ubahStatusPasien');

        Route::get('laporan', 'LaporanController@index')->name('laporan.index');
        Route::get('laporan-cari', 'LaporanController@cari')->name('laporan.cari');
        Route::get('laporan/export/', 'ReservasiAdminController@export')->name('reservasi.export');

        Route::get('pasien', 'CalonPasienController@index')->name('pasien.index');
        Route::post('pasien/import', 'CalonPasienController@import')->name('pasien.import');
        Route::get('download/template-import', 'CalonPasienController@download')->name('pasien.download-template');
    });
});

Route::group(['middleware' => ['auth','role:Super Admin|Dokter|Layanan Reservasi'], 'prefix' => 'table'], function () {
    Route::get('data-user', 'UserController@getData');
    Route::get('data-pertanyaan', 'PertanyaanController@getData');
    Route::get('data-monitoring', 'MonitoringController@getData');
    Route::get('data-skor', 'HasilSkorController@getData');
    Route::get('data-jamsesi', 'JamSesiController@getData');
    Route::get('data-reservasiadmin', 'ReservasiAdminController@getData');
    Route::get('data-sesi', 'SesiController@getData');
    Route::get('data-poli', 'PoliController@getData');
    Route::get('data-poli-hari', 'PoliHariController@getData');
    Route::get('data-reservasilayanan', 'LayananController@getData');
    Route::get('data-reservasi/pasien-lama', 'LayananController@getDataPasienLama');
    Route::get('data-antrian', 'ReservasiAdminController@getAntrian');
    Route::get('data-pasien', 'CalonPasienController@getData');
});


Route::group(['middleware' => ['auth','role:Super Admin'],'prefix' => 'delete'], function () {
    Route::get('data-user/{id}', 'UserController@destroy')->name('user.destroy');
    Route::get('data-pertanyaan/{id}', 'PertanyaanController@destroy')->name('pertanyaan.destroy');
    Route::get('data-monitoring/{id}', 'MonitoringController@destroy')->name('monitoring.destroy');
    Route::get('data-skor/{id}', 'HasilSkorController@destroy')->name('skor.destroy');
    Route::get('data-jamsesi/{id}', 'JamSesiController@destroy')->name('jamsesi.destroy');
    Route::get('data-sesi/{id}', 'SesiController@destroy')->name('sesi.destroy');
    Route::get('data-poli/{id}', 'PoliController@destroy')->name('poli.destroy');
});

Route::group(['prefix'=>'select2'], function() {
    Route::get('data/{slug}/{id}', 'DaerahController@getData');
    Route::get('data-kabupaten', 'DaerahController@getDataKabupaten');
    Route::get('data-kecamatan', 'DaerahController@getDataKecamatan');
    Route::get('data-kelurahan', 'DaerahController@getDataKelurahan');
});

Route::get('/', function(){
    return view('pasien.login');
});

Route::group(['prefix'=>'/'], function(){
    Auth::routes();
    Route::group(['middleware' => ['auth','role:Calon Pasien|Layanan Reservasi']], function () {
        Route::get('list', 'ReservasiController@listCalonPasien')->name('pasien.list');

        Route::get('informasi-jadwal', 'SesiController@jadwal')->name('jadwal.index');
        Route::get('informasi-jadwal/get-jadwal', 'SesiController@getJadwal')->name('jadwal.getData');

        Route::get('reservasi', 'ReservasiController@index')->name('pasien.reservasi');
        Route::get('reservasi/create', 'ReservasiController@create')->name('reservasi.create');
        Route::post('reservasi/store/{id}', 'ReservasiController@store')->name('reservasi.store');
        Route::get('reservasi/{id}', 'ReservasiController@show')->name('reservasi.show');

        Route::resource('calon-pasien', 'CalonPasienController')->except('destroy');

        Route::put('calon-pasien/isi-data/{id}', 'CalonPasienController@isiDataPut')->name('calon-pasien.isiDataPut');
        Route::get('calon-pasien/isi-data/{id}', 'CalonPasienController@isiData')->name('calon-pasien.isiData');

        Route::get('delete/data-calon-pasien/{id}', 'CalonPasienController@destroy')->name('calon-pasien.destroy');
    });
    Route::get('table/data-calon-pasien', 'ReservasiController@getData');
});

Route::get('pasien/reservasi', 'ReservasiController@reservasiNoLogin')->name('reservasi.noLogin');
Route::post('pasien/reservasi-store', 'ReservasiController@reservasiNoLoginStore')->name('reservasi.reservasiNoLoginStore');
Route::get('pasien/reservasi/{kode}', 'ReservasiController@reservasiNoLoginShow')->name('reservasi.noLoginShow');
Route::get('reservasi/batal/{reservasi_id}', 'ReservasiController@batal')->name('reservasi.batal');
Route::get('pasien/reservasi-unduh/{kode}', 'ReservasiController@reservasiNoLoginUnduh')->name('reservasi.noLoginUnduh');
Route::get('reservasi-kode/{kode}', 'ReservasiController@reservasiNoLoginShow')->name('reservasi.lihat');

Route::get('info-antrian', 'ReservasiAdminController@infoAntrian')->name('infoAntrian');

Route::get('screening/create/{reservasi_id}', 'ScreeningController@create')->name('screening.create');
Route::post('screening/store/{reservasi_id}', 'ScreeningController@store')->name('screening.store');

Route::get('screening', 'ScreeningController@createUmum')->name('screening');
Route::post('screening/store', 'ScreeningController@storeUmum')->name('screeningUmum.store');

Route::get('hasil-screening/{reservasi_id}', 'ReservasiController@api_detail')->name('screening.show');

Route::get('reservasi/cek/{poli}', 'ReservasiController@poli')->name('reservasi.poli');
Route::get('reservasi/cek/{poli}/{tanggal}', 'ReservasiController@tanggal')->name('reservasi.tanggal');
Route::get('reservasi/cek/{poli}/{tanggal}/{jam}', 'ReservasiController@jam')->name('reservasi.jam');

Route::group(['middleware' => ['auth','role:Super Admin|Dokter|Calon Pasien|Layanan Reservasi']], function () {
      Route::get('/home', function(){
        if (Auth::user()->hasAnyRole(['Super Admin','Dokter'])) {
            return redirect()->route('reservasiadmin.index');
        } elseif(Auth::user()->hasRole('Calon Pasien')) {
            return redirect()->route('pasien.list');
        } elseif(Auth::user()->hasRole('Layanan Reservasi')) {
            return redirect()->route('layanan.index');
        } else {
            Auth::logout();
            return redirect()->route('login');
        }
      })->name('home');
});




// Route::get('antrian', function() {
//     return view('antrian');
// });
Route::get('antrian', 'ReservasiAdminController@antrian')->name('antrian');
Route::get('table-antrian', 'ReservasiAdminController@getAntrian')->name('antrian.table');

Route::get('voice-caller','ReservasiAdminController@voiceCaller');

Route::get('event', function(){
    event(new App\Events\InfoAntrianEvent('InfoAntrianEvent'));
});

app/Http/Controllers/CalonPasienController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\CalonPasien;
use DB;
use Auth;
use App\Imports\CalonPasienImport;
use Maatwebsite\Excel\Facades\Excel;
use Storage;

class CalonPasienController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pasien.index');
    }

    public function getData(Request $request)
    {
        $data = CalonPasien::all();
        return datatables()->of($data)->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('pasien.calon-pasien.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate(request(),
        [
        'nama' => 'required',
        'nomor_telepon' => 'required|between:10,14',
        'nik' => 'required|digits:16',
        'kartu_bpjs_atau_kartu_sehat' => 'required',
        // 'nomor_bpjs_atau_kartu_sehat' => '',
        ]
        );
        if ($request->kartu_bpjs_atau_kartu_sehat == 'ada') {
        $nomor_bpjs_atau_kartu_sehat = $request->nomor_bpjs_atau_kartu_sehat;
        } else {
        $nomor_bpjs_atau_kartu_sehat = NULL;
        }

        $calonPasien = new CalonPasien();
        $calonPasien->nama = $request->nama;
        $calonPasien->no_telepon = $request->nomor_telepon;
        $calonPasien->nik = $request->nik;
        $calonPasien->no_bpjs = $nomor_bpjs_atau_kartu_sehat;
        $calonPasien->tipe = 'child';
        $calonPasien->created_by = Auth::user()->id;
        $calonPasien->save();

        return redirect()->route('pasien.list');
    }

    public function import(Request $request)
    {
        $this->validate(request(),
        [
            'file' => 'required',
        ]);
        $file = $request->file('file');
        $import = new CalonPasienImport();
        $import->import($file);
        return redirect()->route('pasien.index');
    }

    public function download()
    {
        return response()->download(public_path('file/Template Import Data Pasien.xlsx'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function edit($id)
     {
         $data = CalonPasien::find($id);
         return view('pasien.calon-pasien.edit',compact('data'));
     }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validate(request(),
      [
          'nama' => 'required',
          'nomor_telepon' => 'required|between:10,14',
          'nik' => 'required|digits:16',
          'kartu_bpjs_atau_kartu_sehat' => 'required',
          // 'nomor_bpjs_atau_kartu_sehat' => '',
      ]
      );
      if ($request->kartu_bpjs_atau_kartu_sehat == 'ada') {
        $nomor_bpjs_atau_kartu_sehat = $request->nomor_bpjs_atau_kartu_sehat;
      } else {
        $nomor_bpjs_atau_kartu_sehat = NULL;
      }

      $calonPasien = CalonPasien::find($id);
      $calonPasien->nama = $request->nama;
      $calonPasien->no_telepon = $request->nomor_telepon;
      $calonPasien->nik = $request->nik;
      $calonPasien->no_bpjs = $nomor_bpjs_atau_kartu_sehat;
      $calonPasien->save();

      return redirect()->route('pasien.list');
    }

    public function isiData($id)
    {
        $data = CalonPasien::find($id);
        return view('pasien.calon-pasien.isi-data',compact('data'));
    }

    public function isiDataPut(Request $request, $id)
    {
      $pasien = $id;
      $this->validate(request(),
      [
          'nama' => 'required',
          'nomor_telepon' => 'required|between:10,14',
          'nik' => 'required|digits:16',
          'kartu_bpjs_atau_kartu_sehat' => 'required',
          // 'nomor_bpjs_atau_kartu_sehat' => '',
      ]
      );
      if ($request->kartu_bpjs_atau_kartu_sehat == 'ada') {
        $nomor_bpjs_atau_kartu_sehat = $request->nomor_bpjs_atau_kartu_sehat;
      } else {
        $nomor_bpjs_atau_kartu_sehat = NULL;
      }

      $calonPasien = CalonPasien::find($id);
      $calonPasien->nama = $request->nama;
      $calonPasien->no_telepon = $request->nomor_telepon;
      $calonPasien->nik = $request->nik;
      $calonPasien->no_bpjs = $nomor_bpjs_atau_kartu_sehat;
      $calonPasien->save();

      return redirect()->route('reservasi.create', compact('pasien'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function destroy($id)
     {
         $user = CalonPasien::find($id);
         $user->delete();
         return response()->json(['data'=>'success delete data']);
     }


     // START OF atoumAssertException

     public function api_index()
     {
         $data = CalonPasien::where('created_by',Auth::user()->id)->get();
         return response()->json([
              'status'      => 'success',
              'result'      => $data
          ]);
     }

     public function api_store(Request $request)
     {
          $this->validate(request(),
          [
            'nama' => 'required',
            'nomor_telepon' => 'required|between:10,14',
            'nik' => 'required|digits:16',
             // 'nomor_bpjs' => 'required',
          ]
          );

          $calonPasien = new CalonPasien();
          $calonPasien->nama = $request->nama;
          $calonPasien->no_telepon = $request->nomor_telepon;
          $calonPasien->nik = $request->nik;
          $calonPasien->no_bpjs = $request->nomor_bpjs_atau_kartu_sehat;
          $calonPasien->tipe = 'child';
          $calonPasien->created_by = Auth::user()->id;
          $calonPasien->save();

          return response()->json([
              'status'      => 'success',
              'result'      => $calonPasien
          ]);
     }

     public function api_update(Request $request, $id)
     {
          $this->validate(request(),
          [
            'nama' => 'required',
            'nomor_telepon' => 'required|between:10,14',
            'nik' => 'required|digits:16',
             // 'nomor_bpjs' => 'required',
          ]
          );

          $calonPasien = CalonPasien::find($id);
          $calonPasien->nama = $request->nama;
          $calonPasien->no_telepon = $request->nomor_telepon;
          $calonPasien->nik = $request->nik;
          $calonPasien->no_bpjs = $request->nomor_bpjs_atau_kartu_sehat;
          $calonPasien->tipe = 'child';
          $calonPasien->created_by = Auth::user()->id;
          $calonPasien->save();

          return response()->json([
              'status'      => 'success',
              'result'      => $calonPasien
          ]);
     }

     public function api_destroy($id)
     {
         $user = CalonPasien::find($id);
         if ($user->tipe == 'root') {
           return response()->json([
               'status'      => 'failed',
               'message'      => 'Tidak bisa menghapus data.'
           ]);
         } else {
           $user->delete();
           return response()->json([
             'status'       => 'success',
             'message'      => 'Data berhasil dihapus.'
           ]);
         }
     }
}

resources/views/pasien/calon-pasien/create.blade.php
@extends('pasien.layouts.app')
@section('content')
<!-- Page header -->
<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4><i class=""></i> <span class="text-semibold">User</span></h4>
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-component">
        <ul class="breadcrumb">
            <li><a href="{{route('pasien.list')}}"><i class="icon-home2 position-left"></i> Dashboard</a></li>
            <li><a href="#">Calon Pasien</a></li>
            <li class="active">Tambah</li>
        </ul>
    </div>
</div>
<!-- /page header -->


<!-- Content area -->
<div class="content">
    <div class="panel panel-flat">
        <div class="panel-body">
            <form class="form-horizontal form-validate-jquery" action="{{route('calon-pasien.store')}}" method="post" enctype="multipart/form-data" files=true>
                {{ csrf_field() }}
                <fieldset class="content-group">
                <legend class="text-bold">Tambah Calon Pasien</legend>
                <div class="form-group">
                    <label class="control-label col-lg-3">Nama <span class="text-danger">*</span></label>
                    <div class="col-lg-9">
                        <input type="text" name="nama" class="form-control" value="{{ old('nama') }}" placeholder="NAMA LENGKAP" required>
                        @if ($errors->has('nama'))
                        <label style="padding-top:7px;color:#F44336;">
                        <strong><i class="fa fa-times-circle"></i> {{ $errors->first('nama') }}</strong>
                        </label>
                        @endif
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-lg-3">Nomor Telepon <span class="text-danger">*</span></label>
                    <div class="col-lg-9">
                        <input type="number" maxlength="14" minlength="10" name="nomor_telepon" class="form-control" value="{{ old('nomor_telepon') }}" placeholder="08**********" required>
                        @if ($errors->has('nomor_telepon'))
                        <label style="padding-top:7px;color:#F44336;">
                        <strong><i class="fa fa-times-circle"></i> {{ $errors->first('nomor_telepon') }}</strong>
                        </label>
                        @endif
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-lg-3">NIK <span class="text-danger">*</span></label>
                    <div class="col-lg-9">
                        <input type="number" name="nik" maxlength="16" minlength="16" class="form-control" value="{{ old('nik') }}" placeholder="16 DIGIT NIK" required>
                        @if ($errors->has('nik'))
                        <label style="padding-top:7px;color:#F44336;">
                        <strong><i class="fa fa-times-circle"></i> {{ $errors->first('nik') }}</strong>
                        </label>
                        @endif
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-lg-3">Kartu BPJS / Kartu Sehat <span class="text-danger">*</span></label>
                    <div class="col-lg-9">
                      <div class="form-group">
                        <label class="radio-inline">
                          <input type="radio" name="kartu_bpjs_atau_kartu_sehat" class="styled" value="ada" required id="ada">
                          Ada
                        </label>
                        <label class="radio-inline">
                          <input type="radio" name="kartu_bpjs_atau_kartu_sehat" class="styled" value="tidak" required id="tidak_ada">
                          Tidak Ada
                        </label>
                      </div>
                      @error('kartu_bpjs_atau_kartu_sehat')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                      @enderror
                    </div>
                </div>
                <div class="form-group" style="display:none" id="bpjs">
                    <label class="control-label col-lg-3"></label>
                    <div class="col-lg-9">
                        <input type="number" name="nomor_bpjs_atau_kartu_sehat" class="form-control" value="{{ old('nomor_bpjs_atau_kartu_sehat') }}" placeholder="NO BPJS / KARTU SEHAT" id="nomor_bpjs_atau_kartu_sehat">
                        @if ($errors->has('nomor_bpjs_atau_kartu_sehat'))
                        <label style="padding-top:7px;color:#F44336;">
                        <strong><i class="fa fa-times-circle"></i> {{ $errors->first('nomor_bpjs_atau_kartu_sehat') }}</strong>
                        </label>
                        @endif
                    </div>
                </div>
                </fieldset>
            <div>

            <div class="col-xs-6">
                <a href="{{route('pasien.list')}}"type="button" class="btn btn-default" id=""> <i class="icon-arrow-left13"></i> Kembali</a>
            </div>
                <div class="col-xs-6 text-right">
                    <button type="submit" class="btn btn-primary bg-primary-800">Simpan <i class="icon-arrow-right14 position-right"></i></button>
                </div>
            </div>

            </form>
        </div>
    </div>
</div>
<!-- /content area -->
@endsection
@push('after_script')
<script type="text/javascript">
  $(document).ready(function(){
    $("input[name='kartu_bpjs_atau_kartu_sehat']").change(function(){
      val = $("input[name='kartu_bpjs_atau_kartu_sehat']:checked").val();
      if (val == 'ada') {
        $("#bpjs").show();
        $("#nomor_bpjs_atau_kartu_sehat").attr('required', '');
      } else {
        $("#bpjs").hide();
        $("#nomor_bpjs_atau_kartu_sehat").removeAttr('required');
      }

    });
  });
</script>
@endpush

resources/views/pasien/calon-pasien/edit.blade.php
@extends('pasien.layouts.app')
@section('content')
<!-- Page header -->
<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4><i class=""></i> <span class="text-semibold">User</span></h4>
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-component">
        <ul class="breadcrumb">
            <li><a href="{{route('pasien.list')}}"><i class="icon-home2 position-left"></i> Dashboard</a></li>
            <li><a href="">Calon Pasien</a></li>
            <li class="active">Ubah</li>
        </ul>
    </div>
</div>
<!-- /page header -->


<!-- Content area -->
<div class="content">
    <div class="panel panel-flat">
        <div class="panel-body">
            <form class="form-horizontal form-validate-jquery" action="{{route('calon-pasien.update',$data->id)}}" method="post" enctype="multipart/form-data" files=true>
            @method('PUT')
            @csrf
                <fieldset class="content-group">
                <legend class="text-bold">Ubah Data</legend>
                <div class="form-group">
                    <label class="control-label col-lg-3">Nama <span class="text-danger">*</span></label>
                    <div class="col-lg-9">
                        <input type="text" name="nama" class="form-control" value="{{ old('nama') ? old('nama') : $data->nama }}" placeholder="" required>
                        @if ($errors->has('nama'))
                        <label style="padding-top:7px;color:#F44336;">
                        <strong><i class="fa fa-times-circle"></i> {{ $errors->first('nama') }}</strong>
                        </label>
                        @endif
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-lg-3">Nomor Telepon <span class="text-danger">*</span></label>
                    <div class="col-lg-9">
                        <input type="number" maxlength="14" minlength="10" name="nomor_telepon" class="form-control" value="{{ old('nomor_telepon') ? old('nomor_telepon') : $data->no_telepon }}" placeholder="" required>
                        @if ($errors->has('nomor_telepon'))
                        <label style="padding-top:7px;color:#F44336;">
                        <strong><i class="fa fa-times-circle"></i> {{ $errors->first('nomor_telepon') }}</strong>
                        </label>
                        @endif
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-lg-3">NIK <span class="text-danger">*</span></label>
                    <div class="col-lg-9">
                        <input type="number" maxlength="16" minlength="16" name="nik" class="form-control" value="{{ old('nik') ? old('nik') : $data->nik }}" placeholder="" required>
                        @if ($errors->has('nik'))
                        <label style="padding-top:7px;color:#F44336;">
                        <strong><i class="fa fa-times-circle"></i> {{ $errors->first('nik') }}</strong>
                        </label>
                        @endif
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-lg-3">Kartu BPJS / Kartu Sehat <span class="text-danger">*</span></label>
                    <div class="col-lg-9">
                      <div class="form-group">
                        <label class="radio-inline">
                          <input type="radio" name="kartu_bpjs_atau_kartu_sehat" class="styled" value="ada" required id="ada" {{ ($data->no_bpjs) ? 'checked' : '' }}>
                          Ada
                        </label>
                        <label class="radio-inline">
                          <input type="radio" name="kartu_bpjs_atau_kartu_sehat" class="styled" value="tidak" required id="tidak_ada" {{ (!$data->no_bpjs) ? 'checked' : '' }}>
                          Tidak Ada
                        </label>
                      </div>
                      @error('kartu_bpjs_atau_kartu_sehat')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                      @enderror
                    </div>
                </div>
                <div class="form-group" style="display:none" id="bpjs">
                    <label class="control-label col-lg-3"></label>
                    <div class="col-lg-9">
                        <input type="number" name="nomor_bpjs_atau_kartu_sehat" class="form-control" value="{{ old('nomor_bpjs_atau_kartu_sehat') ? old('nomor_bpjs_atau_kartu_sehat') : $data->no_bpjs }}" placeholder="NO BPJS / KARTU SEHAT" id="nomor_bpjs_atau_kartu_sehat">
                        @if ($errors->has('nomor_bpjs_atau_kartu_sehat'))
                        <label style="padding-top:7px;color:#F44336;">
                        <strong><i class="fa fa-times-circle"></i> {{ $errors->first('nomor_bpjs_atau_kartu_sehat') }}</strong>
                        </label>
                        @endif
                    </div>
                </div>
                </fieldset>
            <div>

            <div class="col-xs-6">
                <a href="{{route('pasien.list')}}"type="button" class="btn btn-default" id=""> <i class="icon-arrow-left13"></i> Kembali</a>
            </div>
                <div class="col-xs-6 text-right">
                    <button type="submit" class="btn btn-primary bg-primary-800">Simpan <i class="icon-arrow-right14 position-right"></i></button>
                </div>
            </div>

            </form>
        </div>
    </div>
</div>
<!-- /content area -->
@endsection
@push('after_script')
<script type="text/javascript">
  $(document).ready(function(){
    var val;
    val = $("input[name='kartu_bpjs_atau_kartu_sehat']:checked").val();
    if (val == "ada") {
      $("#bpjs").show();
      $("#nomor_bpjs_atau_kartu_sehat").attr('required', '');
    }
    $("input[name='kartu_bpjs_atau_kartu_sehat']").change(function(){
      val = $("input[name='kartu_bpjs_atau_kartu_sehat']:checked").val();
      if (val == 'ada') {
        $("#bpjs").show();
        $("#nomor_bpjs_atau_kartu_sehat").attr('required', '');
      } else {
        $("#bpjs").hide();
        $("#nomor_bpjs_atau_kartu_sehat").removeAttr('required');
      }

    });
  });
</script>
@endpush