routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin'], function () {
    Auth::routes();
    Route::group(['middleware' => ['auth','role:Super Admin|Dokter|Layanan Reservasi|Calon Pasien']], function () {
      Route::resource('user', 'UserController')->except('destroy');
      Route::put('user/profile/{id}', 'UserController@updateProfil')->name('user.update-profil');
      Route::put('user/profile/password/{id}', 'UserController@updatePassword')->name('user.update-password');
    });
    Route::group(['middleware' => ['auth','role:Super Admin|Dokter|Layanan Reservasi']], function () {
        Route::resource('dashboard', 'DashboardController');
        Route::resource('pertanyaan', 'PertanyaanController')->except('destroy');
        Route::resource('monitoring', 'MonitoringController')->except('destroy');
        Route::resource('skor', 'HasilSkorController')->except('destroy');
        Route::resource('jamsesi', 'JamSesiController')->except('destroy');
        Route::resource('reservasiadmin', 'ReservasiAdminController')->except('destroy');
        Route::resource('poli', 'PoliController')->except('destroy');


        Route::get('polihari/{poli_id}', 'PoliHariController@index')->name('polihari.index');

        Route::get('sesi/{poli_hari_id}', 'SesiController@index')->name('sesi.index');
        Route::get('sesi-create/create', 'SesiController@create')->name('sesi.create');
        Route::post('sesi/store', 'SesiController@store')->name('sesi.store');
        Route::get('sesi/edit/{id}', 'SesiController@edit')->name('sesi.edit');
        Route::put('sesi/update/{id}', 'SesiController@update')->name('sesi.update');

        Route::get('layanan', 'LayananController@index')->name('layanan.index');
        Route::get('layanan/reservasi/{id}', 'LayananController@reservasi')->name('layanan.reservasi');
        Route::get('layanan/ubah-status/{id}', 'LayananController@statusUpdate')->name('layanan.statusUpdate');

        Route::get('layanan/pasien-lama', 'LayananController@pasienLama')->name('layanan.pasienLama');
        Route::get('layanan/pasien-lama/create/{pasien_id}', 'LayananController@pasienLamaCreate')->name('layanan.pasienLamaCreate');
        Route::post('layanan/pasien-lama/store/{pasien_id}', 'LayananController@pasienLamaStore')->name('layanan.pasienLamaStore');

        Route::get('layanan/pasien-baru', 'LayananController@pasienBaru')->name('layanan.pasienBaru');
        Route::post('layanan/pasien-baru/store', 'LayananController@pasienBaruStore')->name('layanan.pasienBaruStore');

        Route::get('layanan/cek/{poli_id}', 'LayananController@poliCek')->name('layanan.poliCek');

        Route::get('panggil-antrian/{antrian}/{kode}', 'ReservasiAdminController@panggilAntrian');
        Route::get('antrian/{tipe}/{antrian}/{kode}', 'ReservasiAdminController@ubahStatusPasien');

        Route::get('laporan', 'LaporanController@index')->name('laporan.index');
        Route::get('laporan-cari', 'LaporanController@cari')->name('laporan.cari');
        Route::get('laporan/export/', 'ReservasiAdminController@export')->name('reservasi.export');

        Route::get('pasien', 'CalonPasienController@index')->name('pasien.index');
        Route::post('pasien/import', 'CalonPasienController@import')->name('pasien.import');
        Route::get('download/template-import', 'CalonPasienController@download')->name('pasien.download-template');
    });
});

Route::group(['middleware' => ['auth','role:Super Admin|Dokter|Layanan Reservasi'], 'prefix' => 'table'], function () {
    Route::get('data-user', 'UserController@getData');
    Route::get('data-pertanyaan', 'PertanyaanController@getData');
    Route::get('data-monitoring', 'MonitoringController@getData');
    Route::get('data-skor', 'HasilSkorController@getData');
    Route::get('data-jamsesi', 'JamSesiController@getData');
    Route::get('data-reservasiadmin', 'ReservasiAdminController@getData');
    Route::get('data-sesi', 'SesiController@getData');
    Route::get('data-poli', 'PoliController@getData');
    Route::get('data-poli-hari', 'PoliHariController@getData');
    Route::get('data-reservasilayanan', 'LayananController@getData');
    Route::get('data-reservasi/pasien-lama', 'LayananController@getDataPasienLama');
    Route::get('data-antrian', 'ReservasiAdminController@getAntrian');
    Route::get('data-pasien', 'CalonPasienController@getData');
});


Route::group(['middleware' => ['auth','role:Super Admin'],'prefix' => 'delete'], function () {
    Route::get('data-user/{id}', 'UserController@destroy')->name('user.destroy');
    Route::get('data-pertanyaan/{id}', 'PertanyaanController@destroy')->name('pertanyaan.destroy');
    Route::get('data-monitoring/{id}', 'MonitoringController@destroy')->name('monitoring.destroy');
    Route::get('data-skor/{id}', 'HasilSkorController@destroy')->name('skor.destroy');
    Route::get('data-jamsesi/{id}', 'JamSesiController@destroy')->name('jamsesi.destroy');
    Route::get('data-sesi/{id}', 'SesiController@destroy')->name('sesi.destroy');
    Route::get('data-poli/{id}', 'PoliController@destroy')->name('poli.destroy');
});

Route::group(['prefix'=>'select2'], function() {
    Route::get('data/{slug}/{id}', 'DaerahController@getData');
    Route::get('data-kabupaten', 'DaerahController@getDataKabupaten');
    Route::get('data-kecamatan', 'DaerahController@getDataKecamatan');
    Route::get('data-kelurahan', 'DaerahController@getDataKelurahan');
});

Route::get('/', function(){
    return view('pasien.login');
});

Route::group(['prefix'=>'/'], function(){
    Auth::routes();
    Route::group(['middleware' => ['auth','role:Calon Pasien|Layanan Reservasi']], function () {
        Route::get('list', 'ReservasiController@listCalonPasien')->name('pasien.list');

        Route::get('informasi-jadwal', 'SesiController@jadwal')->name('jadwal.index');
        Route::get('informasi-jadwal/get-jadwal', 'SesiController@getJadwal')->name('jadwal.getData');

        Route::get('reservasi', 'ReservasiController@index')->name('pasien.reservasi');
        Route::get('reservasi/create', 'ReservasiController@create')->name('reservasi.create');
        Route::post('reservasi/store/{id}', 'ReservasiController@store')->name('reservasi.store');
        Route::get('reservasi/{id}', 'ReservasiController@show')->name('reservasi.show');

        Route::resource('calon-pasien', 'CalonPasienController')->except('destroy');

        Route::put('calon-pasien/isi-data/{id}', 'CalonPasienController@isiDataPut')->name('calon-pasien.isiDataPut');
        Route::get('calon-pasien/isi-data/{id}', 'CalonPasienController@isiData')->name('calon-pasien.isiData');

        Route::get('delete/data-calon-pasien/{id}', 'CalonPasienController@destroy')->name('calon-pasien.destroy');
    });
    Route::get('table/data-calon-pasien', 'ReservasiController@getData');
});

Route::get('pasien/reservasi', 'ReservasiController@reservasiNoLogin')->name('reservasi.noLogin');
Route::post('pasien/reservasi-store', 'ReservasiController@reservasiNoLoginStore')->name('reservasi.reservasiNoLoginStore');
Route::get('pasien/reservasi/{kode}', 'ReservasiController@reservasiNoLoginShow')->name('reservasi.noLoginShow');
Route::get('reservasi/batal/{reservasi_id}', 'ReservasiController@batal')->name('reservasi.batal');
Route::get('pasien/reservasi-unduh/{kode}', 'ReservasiController@reservasiNoLoginUnduh')->name('reservasi.noLoginUnduh');
Route::get('reservasi-kode/{kode}', 'ReservasiController@reservasiNoLoginShow')->name('reservasi.lihat');

Route::get('info-antrian', 'ReservasiAdminController@infoAntrian')->name('infoAntrian');

Route::get('screening/create/{reservasi_id}', 'ScreeningController@create')->name('screening.create');
Route::post('screening/store/{reservasi_id}', 'ScreeningController@store')->name('screening.store');

Route::get('screening', 'ScreeningController@createUmum')->name('screening');
Route::post('screening/store', 'ScreeningController@storeUmum')->name('screeningUmum.store');

Route::get('hasil-screening/{reservasi_id}', 'ReservasiController@api_detail')->name('screening.show');

Route::get('reservasi/cek/{poli}', 'ReservasiController@poli')->name('reservasi.poli');
Route::get('reservasi/cek/{poli}/{tanggal}', 'ReservasiController@tanggal')->name('reservasi.tanggal');
Route::get('reservasi/cek/{poli}/{tanggal}/{jam}', 'ReservasiController@jam')->name('reservasi.jam');

Route::group(['middleware' => ['auth','role:Super Admin|Dokter|Calon Pasien|Layanan Reservasi']], function () {
      Route::get('/home', function(){
        if (Auth::user()->hasAnyRole(['Super Admin','Dokter'])) {
            return redirect()->route('reservasiadmin.index');
        } elseif(Auth::user()->hasRole('Calon Pasien')) {
            return redirect()->route('pasien.list');
        } elseif(Auth::user()->hasRole('Layanan Reservasi')) {
            return redirect()->route('layanan.index');
        } else {
            Auth::logout();
            return redirect()->route('login');
        }
      })->name('home');
});




// Route::get('antrian', function() {
//     return view('antrian');
// });
Route::get('antrian', 'ReservasiAdminController@antrian')->name('antrian');
Route::get('table-antrian', 'ReservasiAdminController@getAntrian')->name('antrian.table');

Route::get('voice-caller','ReservasiAdminController@voiceCaller');

Route::get('event', function(){
    event(new App\Events\InfoAntrianEvent('InfoAntrianEvent'));
});

app/Warga.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Warga extends Model
{
  protected $table = 'wargas';
  protected $guarded = ['created_at'];
  public $timestamps = true;

  public function provinsi(){
    return $this->belongsTo('App\Models\Province', 'province_id', 'id');
  }
  public function kabupaten(){
    return $this->belongsTo('App\Models\Regency', 'regency_id', 'id');
  }
  public function kecamatan(){
    return $this->belongsTo('App\Models\District', 'district_id', 'id');
  }
  public function kelurahan(){
    return $this->belongsTo('App\Models\Village', 'village_id', 'id');
  }
}

resources/views/warga/layouts/app.backup.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/warga/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Lapor COVID19</title>

	<!-- Global stylesheets -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
	<link href="{{asset('css/icons/icomoon/styles.css')}}" rel="stylesheet" type="text/css">
	<link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet" type="text/css">
	<link href="{{asset('css/core.css')}}" rel="stylesheet" type="text/css">
	<link href="{{asset('css/components.css')}}" rel="stylesheet" type="text/css">
	<link href="{{asset('css/colors.min.css')}}" rel="stylesheet" type="text/css">

	<link href="{{ asset('DataTables/DataTables-1.10.18/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
  	<link href="{{ asset('DataTables/Select-1.2.6/css/select.bootstrap4.min.css') }}" rel="stylesheet">
	<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" rel="stylesheet" />

	<link href="{{asset('css/icons/fontawesome/styles.min.css')}}" rel="stylesheet" type="text/css">
	<!-- /global stylesheets -->
	@stack('after_style')

	<!-- Core JS files -->
	<script type="text/javascript" src="{{asset('js/libraries/jquery.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('js/libraries/bootstrap.min.js')}}"></script>
	<!-- /core JS files -->

	<!-- Theme JS files -->
	<script type="text/javascript" src="{{asset('js/app.min.js')}}"></script>
	<!-- /theme JS files -->

	<script src="{{ asset('DataTables/jquery.dataTables.min.js') }}" ></script>
  <script src="{{ asset('DataTables/dataTables.bootstrap4.min.js') }}" ></script>
	<!-- /theme JS files -->

	<!-- Core JS files -->
	<script type="text/javascript" src="{{asset('js/plugins/loaders/pace.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('js/plugins/loaders/blockui.min.js')}}"></script>
	<!-- /core JS files -->

	<!-- Theme JS files -->
	<script type="text/javascript" src="{{asset('js/plugins/forms/validation/validate.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('js/plugins/forms/selects/bootstrap_multiselect.js')}}"></script>
	<script type="text/javascript" src="{{asset('js/plugins/forms/inputs/touchspin.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('js/plugins/forms/selects/select2.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('js/plugins/forms/styling/switch.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('js/plugins/forms/styling/switchery.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('js/plugins/forms/styling/uniform.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('js/libraries/jquery_ui/interactions.min.js')}}"></script>

	<script type="text/javascript" src="{{asset('js/pages/form_validation.js')}}"></script>
	<script type="text/javascript" src="{{asset('js/pages/form_select2.js')}}"></script>
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

	<!-- Input upload picture -->
	<script type="text/javascript" src="{{asset('js/plugins/uploaders/fileinput.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('js/pages/uploader_bootstrap.js')}}"></script>
	<!-- /Input upload picture -->
	@stack('after_script')

</head>

<body>
	<!-- Main navbar -->
	<div class="navbar navbar-inverse bg-primary-800">
		<div class="navbar-header" style="padding-left:25px">
			<!-- <a href="#"><img src="{{asset('img/web_transparent_fit_ruko_logo_v2_white.png')}}" alt="" style="height:47px"></a> -->
			<h5 style="height:20px">Lapor COVID-19 </h5>
		</div>
	</div>
	<!-- /main navbar -->
	<!-- Page container -->
	<div class="page-container">
		<!-- Page content -->
		<div class="page-content">
			<!-- Main content -->
			<div class="content-wrapper">
			@yield('content')
			</div>
			<!-- /main content -->
		</div>
		<!-- /page content -->
	</div>
	<!-- /page container -->
	{{-- @include('sweetalert::alert') --}}
</body>
</html>

resources/views/warga/layouts/sidebar.blade.php
<div class="sidebar-category sidebar-category-visible">
    <div class="category-content no-padding">
        <ul class="navigation navigation-main navigation-accordion">

            <!-- Main -->
            <li class="navigation-header"><span>Main</span> <i class="icon-menu" title="Main pages"></i></li>
            <li><a href="#"><i class="icon-home4"></i><span>Dashboard</span></a></li>
            @if(Auth::user()->hasRole('Super Admin'))
            
            <li><a href="{{route('pertanyaan.index')}}"><i class="icon-help"></i><span>Pertanyaan</span></a></li>

            <li><a href="{{route('user.index')}}"><i class="icon-user"></i><span>User</span></a></li>
            <!-- /main -->
            @endif
        </ul>
    </div>
</div>