routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin'], function () {
    Auth::routes();
    Route::group(['middleware' => ['auth','role:Super Admin|Dokter|Layanan Reservasi|Calon Pasien']], function () {
      Route::resource('user', 'UserController')->except('destroy');
      Route::put('user/profile/{id}', 'UserController@updateProfil')->name('user.update-profil');
      Route::put('user/profile/password/{id}', 'UserController@updatePassword')->name('user.update-password');
    });
    Route::group(['middleware' => ['auth','role:Super Admin|Dokter|Layanan Reservasi']], function () {
        Route::resource('dashboard', 'DashboardController');
        Route::resource('pertanyaan', 'PertanyaanController')->except('destroy');
        Route::resource('monitoring', 'MonitoringController')->except('destroy');
        Route::resource('skor', 'HasilSkorController')->except('destroy');
        Route::resource('jamsesi', 'JamSesiController')->except('destroy');
        Route::resource('reservasiadmin', 'ReservasiAdminController')->except('destroy');
        Route::resource('poli', 'PoliController')->except('destroy');


        Route::get('polihari/{poli_id}', 'PoliHariController@index')->name('polihari.index');

        Route::get('sesi/{poli_hari_id}', 'SesiController@index')->name('sesi.index');
        Route::get('sesi-create/create', 'SesiController@create')->name('sesi.create');
        Route::post('sesi/store', 'SesiController@store')->name('sesi.store');
        Route::get('sesi/edit/{id}', 'SesiController@edit')->name('sesi.edit');
        Route::put('sesi/update/{id}', 'SesiController@update')->name('sesi.update');

        Route::get('layanan', 'LayananController@index')->name('layanan.index');
        Route::get('layanan/reservasi/{id}', 'LayananController@reservasi')->name('layanan.reservasi');
        Route::get('layanan/ubah-status/{id}', 'LayananController@statusUpdate')->name('layanan.statusUpdate');

        Route::get('layanan/pasien-lama', 'LayananController@pasienLama')->name('layanan.pasienLama');
        Route::get('layanan/pasien-lama/create/{pasien_id}', 'LayananController@pasienLamaCreate')->name('layanan.pasienLamaCreate');
        Route::post('layanan/pasien-lama/store/{pasien_id}', 'LayananController@pasienLamaStore')->name('layanan.pasienLamaStore');

        Route::get('layanan/pasien-baru', 'LayananController@pasienBaru')->name('layanan.pasienBaru');
        Route::post('layanan/pasien-baru/store', 'LayananController@pasienBaruStore')->name('layanan.pasienBaruStore');

        Route::get('layanan/cek/{poli_id}', 'LayananController@poliCek')->name('layanan.poliCek');

        Route::get('panggil-antrian/{antrian}/{kode}', 'ReservasiAdminController@panggilAntrian');
        Route::get('antrian/{tipe}/{antrian}/{kode}', 'ReservasiAdminController@ubahStatusPasien');

        Route::get('laporan', 'LaporanController@index')->name('laporan.index');
        Route::get('laporan-cari', 'LaporanController@cari')->name('laporan.cari');
        Route::get('laporan/export/', 'ReservasiAdminController@export')->name('reservasi.export');

        Route::get('pasien', 'CalonPasienController@index')->name('pasien.index');
        Route::post('pasien/import', 'CalonPasienController@import')->name('pasien.import');
        Route::get('download/template-import', 'CalonPasienController@download')->name('pasien.download-template');
    });
});

Route::group(['middleware' => ['auth','role:Super Admin|Dokter|Layanan Reservasi'], 'prefix' => 'table'], function () {
    Route::get('data-user', 'UserController@getData');
    Route::get('data-pertanyaan', 'PertanyaanController@getData');
    Route::get('data-monitoring', 'MonitoringController@getData');
    Route::get('data-skor', 'HasilSkorController@getData');
    Route::get('data-jamsesi', 'JamSesiController@getData');
    Route::get('data-reservasiadmin', 'ReservasiAdminController@getData');
    Route::get('data-sesi', 'SesiController@getData');
    Route::get('data-poli', 'PoliController@getData');
    Route::get('data-poli-hari', 'PoliHariController@getData');
    Route::get('data-reservasilayanan', 'LayananController@getData');
    Route::get('data-reservasi/pasien-lama', 'LayananController@getDataPasienLama');
    Route::get('data-antrian', 'ReservasiAdminController@getAntrian');
    Route::get('data-pasien', 'CalonPasienController@getData');
});


Route::group(['middleware' => ['auth','role:Super Admin'],'prefix' => 'delete'], function () {
    Route::get('data-user/{id}', 'UserController@destroy')->name('user.destroy');
    Route::get('data-pertanyaan/{id}', 'PertanyaanController@destroy')->name('pertanyaan.destroy');
    Route::get('data-monitoring/{id}', 'MonitoringController@destroy')->name('monitoring.destroy');
    Route::get('data-skor/{id}', 'HasilSkorController@destroy')->name('skor.destroy');
    Route::get('data-jamsesi/{id}', 'JamSesiController@destroy')->name('jamsesi.destroy');
    Route::get('data-sesi/{id}', 'SesiController@destroy')->name('sesi.destroy');
    Route::get('data-poli/{id}', 'PoliController@destroy')->name('poli.destroy');
});

Route::group(['prefix'=>'select2'], function() {
    Route::get('data/{slug}/{id}', 'DaerahController@getData');
    Route::get('data-kabupaten', 'DaerahController@getDataKabupaten');
    Route::get('data-kecamatan', 'DaerahController@getDataKecamatan');
    Route::get('data-kelurahan', 'DaerahController@getDataKelurahan');
});

Route::get('/', function(){
    return view('pasien.login');
});

Route::group(['prefix'=>'/'], function(){
    Auth::routes();
    Route::group(['middleware' => ['auth','role:Calon Pasien|Layanan Reservasi']], function () {
        Route::get('list', 'ReservasiController@listCalonPasien')->name('pasien.list');

        Route::get('informasi-jadwal', 'SesiController@jadwal')->name('jadwal.index');
        Route::get('informasi-jadwal/get-jadwal', 'SesiController@getJadwal')->name('jadwal.getData');

        Route::get('reservasi', 'ReservasiController@index')->name('pasien.reservasi');
        Route::get('reservasi/create', 'ReservasiController@create')->name('reservasi.create');
        Route::post('reservasi/store/{id}', 'ReservasiController@store')->name('reservasi.store');
        Route::get('reservasi/{id}', 'ReservasiController@show')->name('reservasi.show');

        Route::resource('calon-pasien', 'CalonPasienController')->except('destroy');

        Route::put('calon-pasien/isi-data/{id}', 'CalonPasienController@isiDataPut')->name('calon-pasien.isiDataPut');
        Route::get('calon-pasien/isi-data/{id}', 'CalonPasienController@isiData')->name('calon-pasien.isiData');

        Route::get('delete/data-calon-pasien/{id}', 'CalonPasienController@destroy')->name('calon-pasien.destroy');
    });
    Route::get('table/data-calon-pasien', 'ReservasiController@getData');
});

Route::get('pasien/reservasi', 'ReservasiController@reservasiNoLogin')->name('reservasi.noLogin');
Route::post('pasien/reservasi-store', 'ReservasiController@reservasiNoLoginStore')->name('reservasi.reservasiNoLoginStore');
Route::get('pasien/reservasi/{kode}', 'ReservasiController@reservasiNoLoginShow')->name('reservasi.noLoginShow');
Route::get('reservasi/batal/{reservasi_id}', 'ReservasiController@batal')->name('reservasi.batal');
Route::get('pasien/reservasi-unduh/{kode}', 'ReservasiController@reservasiNoLoginUnduh')->name('reservasi.noLoginUnduh');
Route::get('reservasi-kode/{kode}', 'ReservasiController@reservasiNoLoginShow')->name('reservasi.lihat');

Route::get('info-antrian', 'ReservasiAdminController@infoAntrian')->name('infoAntrian');

Route::get('screening/create/{reservasi_id}', 'ScreeningController@create')->name('screening.create');
Route::post('screening/store/{reservasi_id}', 'ScreeningController@store')->name('screening.store');

Route::get('screening', 'ScreeningController@createUmum')->name('screening');
Route::post('screening/store', 'ScreeningController@storeUmum')->name('screeningUmum.store');

Route::get('hasil-screening/{reservasi_id}', 'ReservasiController@api_detail')->name('screening.show');

Route::get('reservasi/cek/{poli}', 'ReservasiController@poli')->name('reservasi.poli');
Route::get('reservasi/cek/{poli}/{tanggal}', 'ReservasiController@tanggal')->name('reservasi.tanggal');
Route::get('reservasi/cek/{poli}/{tanggal}/{jam}', 'ReservasiController@jam')->name('reservasi.jam');

Route::group(['middleware' => ['auth','role:Super Admin|Dokter|Calon Pasien|Layanan Reservasi']], function () {
      Route::get('/home', function(){
        if (Auth::user()->hasAnyRole(['Super Admin','Dokter'])) {
            return redirect()->route('reservasiadmin.index');
        } elseif(Auth::user()->hasRole('Calon Pasien')) {
            return redirect()->route('pasien.list');
        } elseif(Auth::user()->hasRole('Layanan Reservasi')) {
            return redirect()->route('layanan.index');
        } else {
            Auth::logout();
            return redirect()->route('login');
        }
      })->name('home');
});




// Route::get('antrian', function() {
//     return view('antrian');
// });
Route::get('antrian', 'ReservasiAdminController@antrian')->name('antrian');
Route::get('table-antrian', 'ReservasiAdminController@getAntrian')->name('antrian.table');

Route::get('voice-caller','ReservasiAdminController@voiceCaller');

Route::get('event', function(){
    event(new App\Events\InfoAntrianEvent('InfoAntrianEvent'));
});

app/Poli.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Poli extends Model
{
  protected $table = 'poli';
  protected $guarded = ['created_at','updated_at'];
  public $timestamps = true;

  public function poliHari()
  {
    return $this->hasMany('App\PoliHari', 'poli_id', 'id');
  }
}

app/Http/Controllers/PoliController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Poli;
use App\Hari;
use App\PoliHari;
use App\Reservasi;
use DB;
use Carbon\Carbon;
use Illuminate\Support\Facades\Input;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Storage;
use File;

class PoliController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('poli.index');
    }

    public function getData(Request $request)
    {
        $data = Poli::all();
        return datatables()->of($data)
        ->addIndexColumn()
        ->addColumn('action', function($row){
            $btn = '<a href="'.route('poli.edit',$row->id).'" class="btn border-info btn-xs text-info-600 btn-flat btn-icon"><i class="icon-pencil6"></i></a>';
            $btn = $btn.'  <button id="delete" class="btn border-warning btn-xs text-warning-600 btn-flat btn-icon"><i class="icon-trash"></i></button>';
            return $btn;
        })
        ->addColumn('jadwal', function($row){
            $poliHari = PoliHari::where('poli_id',$row->id)->first()->id;
            $btn = '<a href="'.route('sesi.index',$poliHari).'" class="btn border-info btn-xs text-info-600 btn-flat btn-icon"><i class="icon-eye"></i> Kelola Jadwal</a>';
            return $btn;
        })
        ->rawColumns(['action','jadwal'])
        ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('poli.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate(request(),
      [
          'poli' => 'required',
          'kode_poli' => 'required',
          'waktu' => 'required',
          'icon' => 'mimes:png,jpg,jpeg|max:800'
      ]
      );
      DB::beginTransaction();
      $poli = new Poli();
      $poli->kode = $request->kode_poli;
      $poli->poli = $request->poli;
      $poli->waktu = $request->waktu;
      if(!empty($request->icon)){
          $file = $request->file('icon');
          $extension = strtolower($file->getClientOriginalExtension());
          $filename = Carbon::now()->format('ymd').rand(1000,9999) . '.' . $extension;
          $img = Image::make($file)->resize(141, 141);
          Storage::put('public/images/icon-poli/' . $filename, $img->encode());
          $poli->icon = $filename;
      }
      $poli->save();

      $hari = Hari::all();
      foreach ($hari as $key => $value) {
        $poliHari = new PoliHari();
        $poliHari->poli_id = $poli->id;
        $poliHari->hari_id = $value->id;
        $poliHari->save();
      }
      DB::commit();
      return redirect()->route('poli.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $data = Poli::find($id);
      return view('poli.edit',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validate(request(),
      [
          'poli' => 'required',
          'kode_poli' => 'required',
          'waktu' => 'required'
      ]
      );

      $poli = Poli::find($id);
      $poli->poli = $request->poli;
      $poli->kode = $request->kode_poli;
      $poli->waktu = $request->waktu;
      if (!empty($request->icon)) {
        if (!empty($poli->icon)) {
          Storage::delete('public/images/icon-poli/'.$poli->icon);
        }
        if (!empty($poli->icon)) {
          Storage::delete('public/images/icon-poli/'.$poli->icon);
        }
        $file = $request->file('icon');
        $extension = strtolower($file->getClientOriginalExtension());
        $filename = Carbon::now()->format('ymd').rand(1000,9999) . '.' . $extension;
        $img = Image::make($file)->resize(141, 141);
        Storage::put('public/images/icon-poli/' . $filename, $img->encode());
        $poli->icon = $filename;
      }
      $poli->save();
      return redirect()->route('poli.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $poli = Poli::find($id);
      $cek_reservasi = Reservasi::where('poli_id',$id)->first();
      if (!empty($cek_reservasi)) {
        return response()->json(['status' => 'failed','message' => 'Data terkait dengan data lain.'],200);
      }
      $poli_hari = PoliHari::where('poli_id',$id)->get();
      foreach ($poli_hari as $key => $value) {
        $value->delete();
      }
      $poli->delete();
      return response()->json(['status' => 'success'],200);
    }

    public function api_index()
    {
        $data = Poli::all();
        return response()->json([
          'status'      => 'success',
          'result'      => $data
        ]);
    }
}

resources/views/poli/create.blade.php
@extends('layouts.app')
@section('content')
<!-- Page header -->
<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4><i class=""></i> <span class="text-semibold">Poli</span></h4>
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-component">
        <ul class="breadcrumb">
            <li><a href="{{route('dashboard.index')}}"><i class="icon-home2 position-left"></i> Dashboard</a></li>
            <li><a href="{{route('poli.index')}}">Poli</a></li>
            <li class="active">Tambah</li>
        </ul>
    </div>
</div>
<!-- /page header -->


<!-- Content area -->
<div class="content">
    <div class="panel panel-flat">
        <div class="panel-body">
            <form class="form-horizontal form-validate-jquery" action="{{route('poli.store')}}" method="post" enctype="multipart/form-data" files=true>
                {{ csrf_field() }}
                <fieldset class="content-group">
                <legend class="text-bold">Tambah Poli</legend>
                <div class="form-group">
                    <label class="control-label col-lg-3">Poli <span class="text-danger">*</span></label>
                    <div class="col-lg-9">
                        <input type="text" name="poli" class="form-control" value="{{old('poli')}}">
                        @if ($errors->has('poli'))
                        <label style="padding-top:7px;color:#F44336;">
                        <strong><i class="fa fa-times-circle"></i> {{ $errors->first('poli') }}</strong>
                        </label>
                        @endif
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-lg-3">Kode Poli <span class="text-danger">*</span></label>
                    <div class="col-lg-9">
                        <input type="text" name="kode_poli" class="form-control" value="{{old('kode_poli')}}">
                        @if ($errors->has('kode_poli'))
                        <label style="padding-top:7px;color:#F44336;">
                        <strong><i class="fa fa-times-circle"></i> {{ $errors->first('kode_poli') }}</strong>
                        </label>
                        @endif
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-lg-3">Waktu Pemeriksaan <span class="text-danger">*</span></label>
                    <div class="col-lg-9">
                        <input type="number" name="waktu" id="waktu" min="1" class="form-control" value="{{old('waktu')}}">
                        @if ($errors->has('waktu'))
                        <label style="padding-top:7px;color:#F44336;">
                        <strong><i class="fa fa-times-circle"></i> {{ $errors->first('waktu') }}</strong>
                        </label>
                        @endif
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-lg-3">Icon <span class="text-danger">*</span>(Rasio 1:1)</label>
                    <div class="col-lg-9">
                        <input type="file" name="icon" class="file-input-custom" data-show-caption="true" data-show-upload="false" accept="image/*">
                        @if ($errors->has('icon'))
                        <label style="padding-top:7px;color:#F44336;">
                          <strong><i class="fa fa-times-circle"></i> {{$errors->first('icon')}}</strong>
                        </label>
                        @endif
                    </div>
                </div>

                </fieldset>
            <div>

            <div class="col-md-4">
                <a href="{{route('poli.index')}}"type="button" class="btn btn-default" id=""> <i class="icon-arrow-left13"></i> Kembali</a>
            </div>
                <div class="col-md-8 text-right">
                    <button type="submit" class="btn btn-primary bg-primary-800">Simpan <i class="icon-arrow-right14 position-right"></i></button>
                </div>
            </div>
            </form>
        </div>
    </div>
</div>
<!-- /content area -->
@endsection

resources/views/poli/edit.blade.php
@extends('layouts.app')
@section('content')
<!-- Page header -->
<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4><i class=""></i> <span class="text-semibold">Poli</span></h4>
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-component">
        <ul class="breadcrumb">
            <li><a href="{{url('admin/dashboard')}}"><i class="icon-home2 position-left"></i> Dashboard</a></li>
            <li><a href="{{route('poli.index')}}">Poli</a></li>
            <li class="active">Ubah</li>
        </ul>
    </div>
</div>
<!-- /page header -->


<!-- Content area -->
<div class="content">
    <div class="panel panel-flat">
        <div class="panel-body">
            <form class="form-horizontal form-validate-jquery" action="{{route('poli.update',$data->id)}}" method="post" enctype="multipart/form-data" files=true>
            @method('PUT')
            @csrf
                <fieldset class="content-group">
                <legend class="text-bold">Ubah Poli</legend>
                <div class="form-group">
                    <label class="control-label col-lg-3">Poli <span class="text-danger">*</span></label>
                    <div class="col-lg-9">
                        <input type="text" name="poli" class="form-control" value="{{$data->poli}}">
                        @if ($errors->has('poli'))
                        <label style="padding-top:7px;color:#F44336;">
                        <strong><i class="fa fa-times-circle"></i> {{ $errors->first('poli') }}</strong>
                        </label>
                        @endif
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-lg-3">Kode Poli <span class="text-danger">*</span></label>
                    <div class="col-lg-9">
                        <input type="text" name="kode_poli" class="form-control" value="{{$data->kode}}">
                        @if ($errors->has('kode_poli'))
                        <label style="padding-top:7px;color:#F44336;">
                        <strong><i class="fa fa-times-circle"></i> {{ $errors->first('kode_poli') }}</strong>
                        </label>
                        @endif
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-lg-3">Waktu Pemeriksaan <span class="text-danger">*</span></label>
                    <div class="col-lg-9">
                        <input type="number" name="waktu" id="waktu" min="1" class="form-control" value="{{$data->waktu}}">
                        @if ($errors->has('waktu'))
                        <label style="padding-top:7px;color:#F44336;">
                        <strong><i class="fa fa-times-circle"></i> {{ $errors->first('waktu') }}</strong>
                        </label>
                        @endif
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-lg-3">Icon <span class="text-danger">*</span>(Rasio 1:1)</label>
                    <div class="col-lg-9">
                        @if(!empty($data->icon))
                        <img style="padding:10px" class="img-responsive" src="{{asset('storage/images/icon-poli/'.$data->icon.'')}}" alt="icon" title="Ubah icon poli" width="100" height="50">
                        @endif
                        <input type="file" name="icon" class="file-input-custom" data-show-caption="true" data-show-upload="false" accept="image/*">
                        @if ($errors->has('icon'))
                        <label style="padding-top:7px;color:#F44336;">
                          <strong><i class="fa fa-times-circle"></i> {{$errors->first('icon')}}</strong>
                        </label>
                        @endif
                    </div>
                </div>


                </fieldset>
            <div>

            <div class="col-md-4">
                <a href="{{route('poli.index')}}"type="button" class="btn btn-default" id=""> <i class="icon-arrow-left13"></i> Kembali</a>
            </div>
                <div class="col-md-8 text-right">
                    <button type="submit" class="btn btn-primary bg-primary-800">Simpan <i class="icon-arrow-right14 position-right"></i></button>
                </div>
            </div>
            </form>
        </div>
    </div>
</div>
<!-- /content area -->
@endsection

resources/views/poli/index.blade.php
@extends('layouts.app')
@section('content')
<!-- Page header -->
<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4><i class=""></i> <span class="text-semibold">Poli</span></h4>
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-component">
        <ul class="breadcrumb">
            <li><a href="#"><i class="icon-home2 position-left"></i> Dashboard</a></li>
            <li class="active">Poli</li>
        </ul>
    </div>
</div>
<!-- /page header -->


<!-- Content area -->
<div class="content">
  <!-- State saving -->
	<div class="panel panel-flat">
    <div style="padding:20px">
      <div class="col-md-1">
        <a href="{{route('poli.create')}}" class="btn btn-primary btn-sm bg-primary-800"><i class="icon-add position-left"></i>Tambah Data</a>
      </div>

      <table id="table-poli" class="table">
  			<thead>
  				<tr>
            <th>Id</th>
            <th width="10px">No</th>
            <th>Poli</th>
            <th>Kode</th>
            <th>Waktu (Menit)</th>
            <th class="col-md-2">Jadwal</th>
  					<th class="col-md-2">Aksi</th>
  				</tr>
  			</thead>
  			<tbody>
  			</tbody>
  		</table>
    </div>
	</div>
	<!-- /state saving -->
</div>
<!-- /content area -->
@endsection

@push('after_script')
<script>
var tablePoli;
  $(document).ready(function(){
		/* tabel user */
    tablePoli = $('#table-poli').DataTable({
      processing	: true,
			serverSide	: true,
			stateSave: true,
      language: {
                  search: "_INPUT_",
                  searchPlaceholder: "Cari data",
                  paginate: {
                    previous: "Sebelumnya",
                    next: "Berikutnya"
                  }
                },
      ajax		: {
          url: "{{ url('table/data-poli') }}",
          type: "GET",
      },

      columns: [
          { data: 'id', name:'id', visible:false},
          { data: 'DT_RowIndex', name:'DT_RowIndex', visible:true},
          { data: 'poli', name:'poli', visible:true},
          { data: 'kode', name:'kode', visible:true},
          { data: 'waktu', name:'waktu', visible:true},
          { data: 'jadwal', name:'jadwal', visible:true},
          { data: 'action', name:'action', visible:true},
      ],
    });

    $('#table-poli tbody').on( 'click', 'button', function () {
        var data = tablePoli.row( $(this).parents('tr') ).data();
          swal({
          text: "Apakah Anda yakin ingin menghapus data ini?",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        })
        .then((willDelete) => {
          if (willDelete) {
            $.ajax({
              url: "{{ url('delete/data-poli') }}"+"/"+data['id'],
              method: 'get',
              success: function(result){
                if (result.status == 'success') {
                  tablePoli.ajax.reload();
                  swal("Data yang dipilih berhasil dihapus!", {
                    icon: "success",
                  });
                } else {
                  swal(result.message, {
                    icon: "error",
                  });
                }
              }
            });
          } else {
            swal("Data Anda aman!");
          }
        });
      });
  });

</script>
@endpush