routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin'], function () {
    Auth::routes();
    Route::group(['middleware' => ['auth','role:Super Admin|Dokter|Layanan Reservasi|Calon Pasien']], function () {
      Route::resource('user', 'UserController')->except('destroy');
      Route::put('user/profile/{id}', 'UserController@updateProfil')->name('user.update-profil');
      Route::put('user/profile/password/{id}', 'UserController@updatePassword')->name('user.update-password');
    });
    Route::group(['middleware' => ['auth','role:Super Admin|Dokter|Layanan Reservasi']], function () {
        Route::resource('dashboard', 'DashboardController');
        Route::resource('pertanyaan', 'PertanyaanController')->except('destroy');
        Route::resource('monitoring', 'MonitoringController')->except('destroy');
        Route::resource('skor', 'HasilSkorController')->except('destroy');
        Route::resource('jamsesi', 'JamSesiController')->except('destroy');
        Route::resource('reservasiadmin', 'ReservasiAdminController')->except('destroy');
        Route::resource('poli', 'PoliController')->except('destroy');


        Route::get('polihari/{poli_id}', 'PoliHariController@index')->name('polihari.index');

        Route::get('sesi/{poli_hari_id}', 'SesiController@index')->name('sesi.index');
        Route::get('sesi-create/create', 'SesiController@create')->name('sesi.create');
        Route::post('sesi/store', 'SesiController@store')->name('sesi.store');
        Route::get('sesi/edit/{id}', 'SesiController@edit')->name('sesi.edit');
        Route::put('sesi/update/{id}', 'SesiController@update')->name('sesi.update');

        Route::get('layanan', 'LayananController@index')->name('layanan.index');
        Route::get('layanan/reservasi/{id}', 'LayananController@reservasi')->name('layanan.reservasi');
        Route::get('layanan/ubah-status/{id}', 'LayananController@statusUpdate')->name('layanan.statusUpdate');

        Route::get('layanan/pasien-lama', 'LayananController@pasienLama')->name('layanan.pasienLama');
        Route::get('layanan/pasien-lama/create/{pasien_id}', 'LayananController@pasienLamaCreate')->name('layanan.pasienLamaCreate');
        Route::post('layanan/pasien-lama/store/{pasien_id}', 'LayananController@pasienLamaStore')->name('layanan.pasienLamaStore');

        Route::get('layanan/pasien-baru', 'LayananController@pasienBaru')->name('layanan.pasienBaru');
        Route::post('layanan/pasien-baru/store', 'LayananController@pasienBaruStore')->name('layanan.pasienBaruStore');

        Route::get('layanan/cek/{poli_id}', 'LayananController@poliCek')->name('layanan.poliCek');

        Route::get('panggil-antrian/{antrian}/{kode}', 'ReservasiAdminController@panggilAntrian');
        Route::get('antrian/{tipe}/{antrian}/{kode}', 'ReservasiAdminController@ubahStatusPasien');

        Route::get('laporan', 'LaporanController@index')->name('laporan.index');
        Route::get('laporan-cari', 'LaporanController@cari')->name('laporan.cari');
        Route::get('laporan/export/', 'ReservasiAdminController@export')->name('reservasi.export');

        Route::get('pasien', 'CalonPasienController@index')->name('pasien.index');
        Route::post('pasien/import', 'CalonPasienController@import')->name('pasien.import');
        Route::get('download/template-import', 'CalonPasienController@download')->name('pasien.download-template');
    });
});

Route::group(['middleware' => ['auth','role:Super Admin|Dokter|Layanan Reservasi'], 'prefix' => 'table'], function () {
    Route::get('data-user', 'UserController@getData');
    Route::get('data-pertanyaan', 'PertanyaanController@getData');
    Route::get('data-monitoring', 'MonitoringController@getData');
    Route::get('data-skor', 'HasilSkorController@getData');
    Route::get('data-jamsesi', 'JamSesiController@getData');
    Route::get('data-reservasiadmin', 'ReservasiAdminController@getData');
    Route::get('data-sesi', 'SesiController@getData');
    Route::get('data-poli', 'PoliController@getData');
    Route::get('data-poli-hari', 'PoliHariController@getData');
    Route::get('data-reservasilayanan', 'LayananController@getData');
    Route::get('data-reservasi/pasien-lama', 'LayananController@getDataPasienLama');
    Route::get('data-antrian', 'ReservasiAdminController@getAntrian');
    Route::get('data-pasien', 'CalonPasienController@getData');
});


Route::group(['middleware' => ['auth','role:Super Admin'],'prefix' => 'delete'], function () {
    Route::get('data-user/{id}', 'UserController@destroy')->name('user.destroy');
    Route::get('data-pertanyaan/{id}', 'PertanyaanController@destroy')->name('pertanyaan.destroy');
    Route::get('data-monitoring/{id}', 'MonitoringController@destroy')->name('monitoring.destroy');
    Route::get('data-skor/{id}', 'HasilSkorController@destroy')->name('skor.destroy');
    Route::get('data-jamsesi/{id}', 'JamSesiController@destroy')->name('jamsesi.destroy');
    Route::get('data-sesi/{id}', 'SesiController@destroy')->name('sesi.destroy');
    Route::get('data-poli/{id}', 'PoliController@destroy')->name('poli.destroy');
});

Route::group(['prefix'=>'select2'], function() {
    Route::get('data/{slug}/{id}', 'DaerahController@getData');
    Route::get('data-kabupaten', 'DaerahController@getDataKabupaten');
    Route::get('data-kecamatan', 'DaerahController@getDataKecamatan');
    Route::get('data-kelurahan', 'DaerahController@getDataKelurahan');
});

Route::get('/', function(){
    return view('pasien.login');
});

Route::group(['prefix'=>'/'], function(){
    Auth::routes();
    Route::group(['middleware' => ['auth','role:Calon Pasien|Layanan Reservasi']], function () {
        Route::get('list', 'ReservasiController@listCalonPasien')->name('pasien.list');

        Route::get('informasi-jadwal', 'SesiController@jadwal')->name('jadwal.index');
        Route::get('informasi-jadwal/get-jadwal', 'SesiController@getJadwal')->name('jadwal.getData');

        Route::get('reservasi', 'ReservasiController@index')->name('pasien.reservasi');
        Route::get('reservasi/create', 'ReservasiController@create')->name('reservasi.create');
        Route::post('reservasi/store/{id}', 'ReservasiController@store')->name('reservasi.store');
        Route::get('reservasi/{id}', 'ReservasiController@show')->name('reservasi.show');

        Route::resource('calon-pasien', 'CalonPasienController')->except('destroy');

        Route::put('calon-pasien/isi-data/{id}', 'CalonPasienController@isiDataPut')->name('calon-pasien.isiDataPut');
        Route::get('calon-pasien/isi-data/{id}', 'CalonPasienController@isiData')->name('calon-pasien.isiData');

        Route::get('delete/data-calon-pasien/{id}', 'CalonPasienController@destroy')->name('calon-pasien.destroy');
    });
    Route::get('table/data-calon-pasien', 'ReservasiController@getData');
});

Route::get('pasien/reservasi', 'ReservasiController@reservasiNoLogin')->name('reservasi.noLogin');
Route::post('pasien/reservasi-store', 'ReservasiController@reservasiNoLoginStore')->name('reservasi.reservasiNoLoginStore');
Route::get('pasien/reservasi/{kode}', 'ReservasiController@reservasiNoLoginShow')->name('reservasi.noLoginShow');
Route::get('reservasi/batal/{reservasi_id}', 'ReservasiController@batal')->name('reservasi.batal');
Route::get('pasien/reservasi-unduh/{kode}', 'ReservasiController@reservasiNoLoginUnduh')->name('reservasi.noLoginUnduh');
Route::get('reservasi-kode/{kode}', 'ReservasiController@reservasiNoLoginShow')->name('reservasi.lihat');

Route::get('info-antrian', 'ReservasiAdminController@infoAntrian')->name('infoAntrian');

Route::get('screening/create/{reservasi_id}', 'ScreeningController@create')->name('screening.create');
Route::post('screening/store/{reservasi_id}', 'ScreeningController@store')->name('screening.store');

Route::get('screening', 'ScreeningController@createUmum')->name('screening');
Route::post('screening/store', 'ScreeningController@storeUmum')->name('screeningUmum.store');

Route::get('hasil-screening/{reservasi_id}', 'ReservasiController@api_detail')->name('screening.show');

Route::get('reservasi/cek/{poli}', 'ReservasiController@poli')->name('reservasi.poli');
Route::get('reservasi/cek/{poli}/{tanggal}', 'ReservasiController@tanggal')->name('reservasi.tanggal');
Route::get('reservasi/cek/{poli}/{tanggal}/{jam}', 'ReservasiController@jam')->name('reservasi.jam');

Route::group(['middleware' => ['auth','role:Super Admin|Dokter|Calon Pasien|Layanan Reservasi']], function () {
      Route::get('/home', function(){
        if (Auth::user()->hasAnyRole(['Super Admin','Dokter'])) {
            return redirect()->route('reservasiadmin.index');
        } elseif(Auth::user()->hasRole('Calon Pasien')) {
            return redirect()->route('pasien.list');
        } elseif(Auth::user()->hasRole('Layanan Reservasi')) {
            return redirect()->route('layanan.index');
        } else {
            Auth::logout();
            return redirect()->route('login');
        }
      })->name('home');
});




// Route::get('antrian', function() {
//     return view('antrian');
// });
Route::get('antrian', 'ReservasiAdminController@antrian')->name('antrian');
Route::get('table-antrian', 'ReservasiAdminController@getAntrian')->name('antrian.table');

Route::get('voice-caller','ReservasiAdminController@voiceCaller');

Route::get('event', function(){
    event(new App\Events\InfoAntrianEvent('InfoAntrianEvent'));
});

resources/views/pasien/index.blade.php
@extends('layouts.app')
@section('content')
<!-- Page header -->
<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4><i class=""></i> <span class="text-semibold">Pasien</span></h4>
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-component">
        <ul class="breadcrumb">
            <li><a href="#"><i class="icon-home2 position-left"></i> Dashboard</a></li>
            <li class="active">Pasien</li>
        </ul>
    </div>
</div>
<!-- /page header -->


<!-- Content area -->
<div class="content">
  <!-- State saving -->
	<div class="panel panel-flat">
    <div style="padding:20px">
        <div class="col-md-3">
            <button id="btn-import" class="btn btn-primary btn-sm bg-primary-800"><i class="icon-add position-left"></i>Import Data</button>
            <a href="{{route('pasien.download-template')}}" class="btn btn-primary btn-sm bg-primary-800"><i class="icon-download position-left"></i>Download Template</a>
        </div>
        <table id="table-pasien" class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nama</th>
                        <th>NIK</th>
                        <th>No HP</th>
                        <th>No BPJS</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
	</div>
	<!-- /state saving -->
</div>
<!-- /content area -->

<div id="modal-import" class="modal fade">
	<div class="modal-dialog">
        <form class="form-horizontal form-validate-jquery" action="{{route('pasien.import')}}" method="post" enctype="multipart/form-data" files=true>
            @csrf
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h5 class="modal-title">Import Data</h5>
                </div>
                <div class="modal-body">
                    <div class="form-group">
  						<div class="row">
  							<div class="col-md-12">
                                <input type="file" name="file" class="form-control" required accept=".xls, .xlsx" id="">
  							</div>
  						</div>
  					</div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary pull-right">Submit</button>
                </div>
            </div>
        </form>
	</div>
</div>
@endsection

@push('after_script')
<script>
var tablePasien;
  $(document).ready(function(){
    $('#btn-import').click(function(){
        $('#modal-import').modal('show');
    });
	/* tabel pasien */
    tablePasien = $('#table-pasien').DataTable({
      processing	: true,
			serverSide	: true,
			stateSave: true,
      language: {
                  search: "_INPUT_",
                  searchPlaceholder: "Cari data",
                  paginate: {
                    previous: "Sebelumnya",
                    next: "Berikutnya"
                  }
                },
      ajax		: {
          url: "{{ url('table/data-pasien') }}",
          type: "GET",
      },

      columns: [
          { data: 'id', name:'id', visible:false},
          { data: 'nama', name:'nama', visible:true},
          { data: 'nik', name:'nik', visible:true},
          { data: 'no_telepon', name:'no_telepon', visible:true},
          { data: 'no_bpjs', name:'no_bpjs', visible:true},
      ],
    });
  });

</script>
@endpush

resources/views/pasien/info-antrian.blade.php
@extends('pasien.layouts.app')
@section('antrian','active')
@section('informasi','active')
@section('content')
<!-- Page header -->
<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4><i class=""></i> <span class="text-semibold">Informasi Antrian Hari Ini</span></h4>
            <label for=""> Update {{\Carbon\Carbon::now()->format('H:i:s')}} - </label>
            <a href="" id="refresh"> <i class="fa fa-refresh"></i> refresh </a>
        </div>
    </div>
    <div class="breadcrumb-line breadcrumb-line-component">
        <ul class="breadcrumb">
            <li><a href="{{route('pasien.list')}}"><i class="icon-home2 position-left"></i> Dashboard</a></li>
            <li class="active">Info Antrian</li>
        </ul>
    </div>
</div>
<!-- /page header -->


<!-- Content area -->
<div class="content">
  <div class="col-lg-12">
      <div class="btn-group col-xs-12" data-toggle="buttons" style="margin:0px;padding:0px">
        @foreach ($poli as $value)
          @if ($value->id == $data->id)
          <label class="btn bg-teal-800 btn-ligh text-center col-md-2 col-sm-3 col-xs-6" style="margin:5px 0px 5px 0px;outline: 1px solid #ddd;">
              <img src="{{asset('storage/images/icon-poli/'.$value->icon.'')}}" alt="error" style="width:60px">
              <br>
              <input type="radio" name="poli" id="poli" value="{{$value->kode}}">{{$value->poli}}
          </label>
          @else
          <label class="btn bg-teal-300 btn-ligh text-center col-md-2 col-sm-3 col-xs-6" style="margin:5px 0px 5px 0px;outline: 1px solid #ddd;">
            <img src="{{asset('storage/images/icon-poli/'.$value->icon.'')}}" alt="error" style="width:60px">
            <br>
            <input type="radio" name="poli" id="poli" value="{{$value->kode}}">{{$value->poli}}
          </label>
          @endif
        @endforeach
      </div>
      <div style="display:none">
        <form action="{{route('infoAntrian')}}" method="get" enctype="multipart/form-data" files=true>
          <input type="" name="kode_poli" value="" id="kode_poli">
          <button type="submit" id="btn-submit">Tambah Sesi</button>
        </form>
      </div>
  </div>
  <!-- State saving -->
  <div class="col-md-12">
      <div class="btn btn-default btn-ligh text-center col-md-12 col-xs-12" style="margin-top:5px">
          <div class="col-md-12">
              <h4 style="margin-bottom:0px;padding:bottom:0px"><b>Poli Umum</b></h4>
              {{$data->total_pasien_terlayani}} dari {{$data->total_pasien}} Pasien Terlayani
              <hr>
          </div>
          <div class="col-sm-12">
            <div class="col-sm-6" style="margin-bottom:10px">
              <span class="label label-flat border-info text-info-600 col-xs-6 col-xs-offset-3">
                <h1 style="margin:0 0 0 0;padding:0 0 0 0"><b>{{ $data->diperiksa ? $data->diperiksa->antrian : '-' }}</b></h1>
              </span>
              <div class="col-xs-12">
                (Sedang Diperiksa)
              </div>
            </div>
            <div class="col-sm-6">
              <span class="label label-flat border-warning text-warning-600 col-xs-6 col-xs-offset-3">
                <h1 style="margin:0 0 0 0;padding:0 0 0 0">
                  <b>
                  @if (!empty($data->antrian_selanjutnya[0]))
                        @if (!empty($data->antrian_selanjutnya->whereNotNull('counter')))
                            @if ($data->antrian_selanjutnya->whereNotNull('counter')->last())
                              {{$data->antrian_selanjutnya->whereNotNull('counter')->last()->antrian}}
                            @else
                              {{$data->antrian_selanjutnya[0]['antrian']}}
                            @endif
                        @else
                            {{$data->antrian_selanjutnya[0]['antrian']}}
                        @endif
                    @else
                        -
                    @endif 
                  </b>
                </h1>
              </span>
              <div class="col-xs-12">
                (Antrian Selanjutnya)
              </div>
            </div>
          </div>
          <div class="col-sm-12">
            <hr>
            <div class="col-xs-12 col-sm-6 col-md-3">
              <div class="table-responsive">
  							<table class="table table-bordered table-framed table-xxs">
  								<thead>
  									<tr class="bg-teal">
  										<th class="text-center">Daftar Antrian</th>
  									</tr>
  								</thead>
  								<tbody>
                    @if(!empty($data->antrian_selanjutnya[0]))
                      @foreach ($data->antrian_selanjutnya as $key => $value)
                      <tr>
                        @if ($value->status == 'Terlewat Pemanggilan')
                        <td>{{$value->antrian}} ({{$value->status}})</td>
                        @else
                        <td>{{$value->antrian}}</td>
                        @endif
                      </tr>
                      @endforeach
                    @else
                      <tr>
                        <td>-</td>
                      </tr>
                    @endif
  								</tbody>
  							</table>
  						</div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
              <div class="table-responsive">
  							<table class="table table-bordered table-framed table-xxs">
  								<thead>
  									<tr class="bg-teal">
  										<th class="text-center">Belum Datang</th>
  									</tr>
  								</thead>
                  <tbody>
                    @if (!empty($data->antrian_belum_datang[0]))
                      @foreach ($data->antrian_belum_datang as $key => $value)
                      <tr>
                        <td>{{$value->antrian}}</td>
                      </tr>
                      @endforeach
                    @else
                      <tr>
                        <td>-</td>
                      </tr>
                    @endif
                  </tbody>
  							</table>
  						</div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
              <div class="table-responsive">
  							<table class="table table-bordered table-framed table-xxs">
  								<thead>
  									<tr class="bg-teal">
  										<th class="text-center">Terlewati</th>
  									</tr>
  								</thead>
                  <tbody>
                    @if (!empty($data->antrian_terlewati[0]))
                      @foreach ($data->antrian_terlewati as $key => $value)
                      <tr>
                        <td>{{$value->antrian}}</td>
                      </tr>
                      @endforeach
                    @else
                      <tr>
                        <td>-</td>
                      </tr>
                    @endif
                  </tbody>
  							</table>
  						</div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
              <div class="table-responsive">
  							<table class="table table-bordered table-framed table-xxs">
  								<thead>
  									<tr class="bg-teal">
  										<th class="text-center">Selesai</th>
  									</tr>
  								</thead>
                  <tbody>
                    @if (!empty($data->antrian_selesai[0]))
                      @foreach ($data->antrian_selesai as $key => $value)
                      <tr>
                        <td>{{$value->antrian}}</td>
                      </tr>
                      @endforeach
                    @else
                      <tr>
                        <td>-</td>
                      </tr>
                    @endif
                  </tbody>
  							</table>
  						</div>
            </div>
          </div>
      </div>
  </div>

	<!-- /state saving -->
</div>
<!-- /content area -->
@endsection

@push('after_style')
@endpush

@push('after_script')
<script>
    $(document).ready(function(){
        $(document).on("change", "input[name='poli']", function () {
            poli = $("input[name='poli']:checked").val()
            $('#kode_poli').val(poli);
            jQuery('#btn-submit').click();
        })
        $( "#refresh" ).click(function() {
          location.reload()
        });
    });
</script>
@endpush

resources/views/pasien/list.blade.php
@extends('pasien.layouts.app')
@section('beranda','active')
@section('content')
<!-- Page header -->
<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4><i class=""></i> <span class="text-semibold">User</span></h4>
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-component">
        <ul class="breadcrumb">
            <li><a href="{{route('pasien.list')}}"><i class="icon-home2 position-left"></i> Dashboard</a></li>
            <li class="active">User</li>
        </ul>
    </div>
</div>
<!-- /page header -->


<!-- Content area -->
<div class="content">
  <!-- State saving -->
	<div class="panel panel-flat">
    <div style="padding:20px">
      <div class="col-md-12">
        <form action="{{route('reservasi.create')}}" method="get" enctype="multipart/form-data" files=true>
          <div class="col-lg-2 col-md-3 col-sm-4 col-xs-12" style="margin-top:5px;padding:0px 2px 0px 2px">
              <a style="width:100%" href="{{route('calon-pasien.create')}}" class="btn btn-primary btn-sm bg-primary-800"><i class="icon-add position-left"></i>Tambah Anggota</a>
          </div>
          <div class="col-lg-2 col-md-3 col-sm-4 col-xs-12" style="margin-top:5px;padding:0px 2px 0px 2px">
            @if ($pasien->count() > 1)
              <a style="width:100%" class="btn btn-orange btn-sm bg-orange-800" id="btn-nama"><i class="icon-book2 position-left"></i>Buat Reservasi</a>
            @else
            <input type="hidden" name="pasien" value="{{$pasien[0]->id}}">
            <button style="width:100%" type="submit" class="btn btn-orange btn-sm bg-orange-800"><i class="icon-book2 position-left"></i>Buat Reservasi</button>
            @endif
          </div>
          <div class="col-lg-2 col-md-3 col-sm-4 col-xs-12" style="margin-top:5px;padding:0px 2px 0px 2px">
            <a style="width:100%" href="{{route('screening')}}" class="btn btn-slate btn-sm bg-slate-800"><i class="icon-eye4 position-left"></i>Screening Covid19</a>
          </div>

        </form>
      </div>

      <table id="table-calon-pasien" class="table">
  			<thead>
  				<tr>
            <th>Id</th>
  					<th width="70%">Nama</th>
            <!-- <th width="15%">Antrian</th> -->
  					<th width="30%">Aksi</th>
  				</tr>
  			</thead>
  			<tbody>
  			</tbody>
  		</table>
    </div>
	</div>
	<!-- /state saving -->
</div>
<!-- /content area -->

<!-- Vertical form modal -->
<div id="modal_name" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h5 class="modal-title">Pilih Nama</h5>
			</div>
        <form class="form-horizontal form-validate-jquery" action="{{route('reservasi.create')}}" method="get" enctype="multipart/form-data" files=true>
  				<div class="modal-body">
  					<div class="form-group">
  						<div class="row">
  							<div class="col-md-12">
                  <select name="pasien" class="form-control select-search" id="pasien">
                      @foreach ($pasien as $key => $value)
                          <option value="{{$value->id}}">{{$value->nama}}</option>
                      @endforeach
                  </select>
  							</div>
  						</div>
  					</div>
            <button type="submit" class="btn btn-primary pull-right">Next</button>
  				</div>
        </form>
				<div class="modal-footer">
					<!-- <button type="button" class="btn btn-link" data-dismiss="modal">Close</button> -->
				</div>
		</div>
	</div>
</div>
<!-- /vertical form modal -->
@endsection

@push('after_style')
  <style>


  </style>
@endpush

@push('after_script')
@push('after_script')
<script>
var tableCalonPasien;
  $(document).ready(function(){
    $('#btn-nama').click(function(){
      $('#modal_name').modal('show');
    });

		/* tabel calon-pasien */
    tableCalonPasien = $('#table-calon-pasien').DataTable({
      processing	: true,
			serverSide	: true,
			stateSave: true,
      language: {
                  search: "_INPUT_",
                  searchPlaceholder: "Cari data",
                  paginate: {
                    previous: "Sebelumnya",
                    next: "Berikutnya"
                  }
                },
      ajax		: {
          url: "{{ url('table/data-calon-pasien') }}",
          type: "GET",
      },

      columns: [
          { data: 'id', name:'id', visible:false},
          { data: 'nama', name:'nama', visible:true},
          // { data: 'antrian', name:'antrian', visible:true},
          { data: 'action', name:'action', visible:true},
      ],
    });

    $('#table-calon-pasien tbody').on( 'click', 'button', function () {
        var data = tableCalonPasien.row( $(this).parents('tr') ).data();
          swal({
          text: "Apakah Anda yakin ingin menghapus data ini?",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        })
        .then((willDelete) => {
          if (willDelete) {
            $.ajax({
              url: "{{ url('delete/data-calon-pasien') }}"+"/"+data['id'],
              method: 'get',
              success: function(result){
                tableCalonPasien.ajax.reload();
                swal("Data yang dipilih berhasil dihapus!", {
                  icon: "success",
                });
              }
            });
          } else {
            swal("Data Anda aman!");
          }
        });
      });
  });

</script>
@endpush
@endpush